-- Generated by scripts/reads/build-seed.mjs from content/reads. Do not edit by hand.
begin;

insert into public.reads (id, title, summary, topic, body, minutes, deck_ids, patterns, card_deck, sort_order, reviewed, status) values
  ('anxiety-from-nowhere', 'Anxiety that seems to come from nowhere', 'Anxiety can have a physical side too. How your cycle, sleep, caffeine and thyroid can play a part.', 'mood', 'Some anxiety has an obvious source. Other times it just appears: a racing heart, a tight chest, a sense of dread with no clear reason. When that happens, it helps to know your body can be part of the story.

## Physical things that can feed anxiety

- **Your cycle.** Some people feel more anxious or on edge in the week before their period, as estrogen and progesterone fall.
- **Perimenopause.** New anxiety in your late 30s or 40s is a common, and often overlooked, sign of hormone changes.
- **Sleep.** After a short night, the brain’s alarm system is more reactive.
- **Caffeine.** It can cause a racing heart and jitters that feel a lot like anxiety, especially on an empty stomach.
- **Long gaps without eating.** Feeling shaky and irritable when hungry can tip into anxiety for some people.
- **Thyroid.** An overactive thyroid can cause a fast heartbeat, restlessness and worry.
- **Alcohol.** The day after can bring a rebound of anxious feelings.

## This doesn’t make it “just hormones”

Anxiety is real whether or not it has a physical trigger, and it deserves care either way. Knowing the physical side simply gives you more ways to help it.

## What can help

- Noting when it shows up, alongside your cycle, sleep and caffeine
- Slow breathing with a longer breath out, which signals the body to settle
- Regular meals, and caffeine earlier in the day
- Talking to someone you trust

## When to talk to your doctor

If anxiety is frequent, gets in the way of daily life, or comes with panic attacks, talk to your doctor. Therapy and medication both help, and a thyroid check can rule out a physical cause. If you’re in crisis in the U.S., call or text 988, or contact your local emergency number.

## Sources

- U.S. National Institute of Mental Health, information on anxiety disorders
- The Menopause Society, information on mood changes in perimenopause
- American Thyroid Association, information on hyperthyroidism', 2, array[]::text[], array[]::text[], 'listening-to-my-body', 91, false, 'published'),
  ('bloating-and-your-cycle', 'Bloating: when it’s your cycle and when to check', 'Bloating around your period is common. Why it happens, and the kind that’s worth getting checked.', 'gut', 'Feeling puffy, tight or heavy in your stomach is one of the most common complaints there is. Often it’s linked to food or your cycle. Sometimes it’s worth a closer look.

## Why it happens around your period

- **Progesterone**, which rises after ovulation, can slow digestion, so things move more slowly and gas builds up.
- **Fluid retention** is common in the days before a period.
- **Prostaglandins**, released as your period starts, can speed the gut up, which is why some people get looser stools on day one.

## Other everyday causes

- Constipation
- Eating quickly, fizzy drinks or swallowing air
- Foods that ferment in the gut, like beans, onions and some sweeteners, especially if you’re sensitive to them
- Stress, which changes how the gut moves
- Irritable bowel syndrome (IBS), which is common in women and can flare around periods

## What can help

- Noticing whether bloating follows your cycle, certain foods or stressful days
- Eating more slowly, and moving after meals
- More fibre and water, increased gradually, to help with constipation

## When to get it checked

See your doctor if bloating:

- Happens most days for three weeks or more
- Comes with feeling full quickly, loss of appetite, pelvic or stomach pain, or needing to pee more often
- Comes with unexplained weight loss, blood in your stool or changes in your bowel habits

These usually have causes that aren’t serious, but persistent bloating is something doctors want to hear about, because occasionally it can be an early sign of ovarian cancer.

## Sources

- NHS, symptoms of ovarian cancer
- ACOG, Premenstrual Syndrome FAQ
- NIDDK, information on gas and irritable bowel syndrome', 2, array[]::text[], array[]::text[], 'my-cycle', 111, false, 'published'),
  ('brain-fog', 'Brain fog: why it happens and when to mention it', 'Losing words, losing your train of thought, feeling slow. Brain fog is common, and it usually has a reason.', 'mood', 'Brain fog isn’t a medical diagnosis, but most people know it when it happens: losing words mid-sentence, rereading the same email, walking into a room and forgetting why. It can be unsettling. It’s also very common, and it often has causes you can do something about.

## Common causes

- **Sleep.** Even a few short nights in a row affect focus and memory.
- **Stress and overload.** When your mind is holding too much, there’s less room for everything else.
- **Hormone changes.** Some people notice fog before their period, after having a baby, or in perimenopause, when shifting estrogen affects the brain.
- **Low iron.** Iron deficiency, with or without anemia, is common in people with heavy periods and can cause tiredness and poor concentration.
- **Thyroid changes.** An underactive thyroid can slow thinking.
- **Low mood or anxiety.** Depression often shows up as trouble concentrating, not only sadness.
- **Long gaps without food or water.**

## What can help

- Protecting sleep and keeping a steady wake time
- Regular meals and water through the day
- Writing things down, so your memory doesn’t have to hold everything
- Noticing when the fog is worse, like certain days of your cycle or after bad nights

## When to talk to your doctor

If brain fog lasts for weeks, is getting worse, or comes with heavy periods, exhaustion, low mood or other changes, mention it. Simple blood tests, like iron (ferritin) and thyroid, can rule out common causes. Get urgent help for sudden confusion, weakness on one side, or trouble speaking.

## Sources

- The Menopause Society, information on memory and brain fog
- American Society of Hematology, information on iron-deficiency anemia
- American Thyroid Association, information on hypothyroidism', 2, array['listening-to-my-body']::text[], array[]::text[], 'listening-to-my-body', 90, false, 'published'),
  ('eating-enough', 'Eating enough: why under-fuelling shows up everywhere', 'Not eating enough for what you do can affect your energy, mood, sleep and cycle. Here’s why.', 'food', 'Most nutrition messages are about eating less. But a lot of women, especially busy or active ones, aren’t eating enough for what their bodies are doing, often without meaning to.

## How it happens

- Skipping breakfast and working through lunch
- Very active weeks without eating more to match
- Long-term dieting, or cutting out whole food groups
- Stress or a hectic stretch that dulls your appetite

## What your body does

When the energy coming in doesn’t cover what you’re using, your body protects itself by turning down things it can put on hold. Your cycle is one of them. Doctors call this low energy availability. The brain can lower its signals to the ovaries, and periods may become irregular or stop. This is called hypothalamic amenorrhea.

Other signs of under-fuelling can include:

- Tiredness, feeling cold, or getting ill more often
- Irritability, low mood and poor concentration
- Trouble sleeping
- Strong cravings, or thinking about food a lot
- Injuries that are slow to heal, like stress fractures

## Why it matters

Estrogen helps protect your bones and heart. Missing periods for a long time can lower bone density, so this is worth taking seriously, even when it feels like just a missed period.

## What can help

Regular meals and snacks, eating more on active days, and including carbohydrates, protein and fat. If you train a lot, a sports dietitian can help you match food to what you do.

## When to talk to your doctor

Talk to your doctor if you’ve missed three periods in a row, you’re not pregnant, and you’ve been very active, stressed or eating less. If food or your body feels hard to think about, it’s okay to ask for help with that too.

## Sources

- ACOG, information on amenorrhea
- International Olympic Committee consensus statement on Relative Energy Deficiency in Sport (REDs)
- Endocrine Society, Functional Hypothalamic Amenorrhea guideline', 2, array['food-cravings-and-me']::text[], array[]::text[], 'energy-and-rhythm', 101, false, 'published'),
  ('how-hormonal-birth-control-works', 'How hormonal birth control works', 'What the pill, patch, ring, implant and hormonal IUD actually do, and why a pill bleed isn’t quite a period.', 'birth-control', 'Hormonal birth control uses versions of hormones your body already makes, estrogen and progestin (a form of progesterone), to prevent pregnancy. Different methods do this in slightly different ways.

## The main types

- **Combined methods** (the pill, patch and ring) contain estrogen and progestin. They mainly work by stopping ovulation.
- **Progestin-only pills** mainly thicken cervical mucus so sperm can’t get through, and some also stop ovulation.
- **The implant and the injection** mainly stop ovulation.
- **Hormonal IUDs** release a small amount of progestin inside the uterus. They thicken cervical mucus and thin the uterine lining. Many people still ovulate.

## Is a pill bleed a period?

Not quite. On combined methods, the bleed during the break week is a withdrawal bleed, caused by the drop in hormones rather than a natural cycle. That’s why it’s often lighter, and why many people can skip the break if their doctor agrees.

## What it can and can’t tell you

Because many methods pause ovulation, your bleeding pattern on birth control doesn’t tell you much about your natural cycle. That isn’t good or bad. It’s just useful to know if you’re trying to understand your body.

## Beyond contraception

Hormonal methods are also used to manage heavy or painful periods, endometriosis, acne and some symptoms of PMOS (formerly PCOS).

## Finding the right fit

The best method is the one that fits your body, your health history and your life. Your doctor can help you weigh the options, and it’s fine to change your mind.

## Sources

- ACOG, Combined Hormonal Birth Control FAQ
- ACOG, Long-Acting Reversible Contraception FAQ
- U.S. Centers for Disease Control and Prevention, contraception information', 2, array[]::text[], array[]::text[], 'my-cycle', 81, false, 'published'),
  ('how-pmos-is-diagnosed', 'How PMOS is diagnosed', 'There’s no single test for PMOS (formerly PCOS). What doctors look for, and questions you can bring.', 'pmos', 'Many people with PMOS (formerly PCOS) live with symptoms for years before anyone connects them. Knowing what doctors look for can help you ask the right questions.

## What doctors look for

In adults, a diagnosis usually needs at least two of these three:

- **Irregular or missing ovulation**, usually showing up as irregular, infrequent or absent periods
- **Signs of higher androgens**, either in blood tests or as symptoms like acne, extra hair on the face, chest or stomach, or thinning hair on the scalp
- **Many follicles on the ovaries** seen on ultrasound, or a high AMH level on a blood test

Other conditions that can look similar, like thyroid problems or high prolactin, are ruled out first.

## Why it gets missed

Symptoms vary a lot. One person has irregular cycles and no acne. Another has fairly regular cycles and noticeable hair growth. Hormonal birth control can also mask irregular periods and acne, so some signs only appear after stopping it.

## The metabolic side

Because PMOS is also a metabolic condition, the international guideline recommends checking blood sugar, cholesterol and blood pressure, and asking about mood and sleep, whatever your weight.

## Questions you might bring

- Could my irregular cycles and these other symptoms be connected?
- Which blood tests would help, and when in my cycle should I have them?
- Should my blood sugar be checked, and how often?
- What are my options if I’m not trying to get pregnant, and if I am?

## Sources

- International Evidence-based Guideline for the Assessment and Management of Polycystic Ovary Syndrome (2023)
- ACOG, Polycystic Ovary Syndrome FAQ
- Endocrine Society, patient information on PCOS', 2, array[]::text[], array[]::text[], 'looking-for-answers', 51, false, 'published'),
  ('insulin-does-more-than-blood-sugar', 'Insulin does more than manage blood sugar', 'Insulin is best known for blood sugar, but it also talks to your ovaries, your appetite and your energy. Here’s why that matters.', 'blood-sugar', 'Insulin usually comes up in conversations about diabetes. But it’s a hormone that affects far more than blood sugar, and it’s one reason symptoms that seem unrelated can share a root.

## What insulin does

After you eat, insulin helps move sugar from your blood into your cells, where it’s used for energy or stored. It also sends signals to the liver, to fat tissue and, importantly for women, to the ovaries.

## When cells stop listening

Sometimes cells respond less well to insulin. This is called insulin resistance. To keep blood sugar in range, the body makes more insulin. Blood sugar tests can look normal for years while insulin is working overtime.

Higher insulin can nudge the ovaries to make more androgens, hormones like testosterone. That’s one reason insulin resistance is closely linked with PMOS (formerly PCOS), irregular cycles, acne and extra hair growth.

It can also show up as:

- Energy dips and strong cravings, especially after carbohydrate-heavy meals
- More weight around the middle, even without changes in how you eat
- Darker, velvety patches of skin on the neck or in skin folds

## What helps

Muscles become more responsive to insulin with regular movement, including a walk after meals. Sleep helps too, and so do meals built around protein and fibre. Some people also benefit from medication, which is a conversation for your doctor.

## When to talk to your doctor

If several of these sound familiar, ask about checking blood sugar markers like fasting glucose and HbA1c. Insulin resistance is common, often silent, and much easier to work with when it’s found early.

## Sources

- NIDDK, information on insulin resistance and prediabetes
- American College of Obstetricians and Gynecologists (ACOG), Polycystic Ovary Syndrome FAQ
- Endocrine Society, patient information on insulin resistance', 2, array['looking-for-answers']::text[], array[]::text[], 'looking-for-answers', 11, false, 'published'),
  ('perimenopause-signs-people-miss', 'Perimenopause signs that aren’t hot flashes', 'Anxiety, broken sleep, heavier periods and brain fog can all be early signs. Why they’re so easy to miss.', 'perimenopause', 'When people picture menopause, they picture hot flashes. But the earliest signs of perimenopause often look nothing like that, which is why so many women don’t connect the dots for years.

## Signs that are easy to miss

- **Anxiety or low mood** that feels new, or stronger than before
- **Waking at night**, sometimes with a racing heart or feeling hot
- **Heavier or closer-together periods**, especially early on
- **Stronger premenstrual symptoms** than you used to have
- **Brain fog**, like losing words or forgetting why you walked into a room
- **Aches and stiffness** in your joints
- **Changes in skin and hair**, like dryness or thinning
- **Needing to pee more often**, or more urinary infections

## Why they get missed

Many of these have other possible causes, and they often arrive during a busy, demanding stage of life. It’s easy to put them down to stress, age or just a hard year.

Blood tests aren’t very reliable for confirming perimenopause either, because hormone levels change so much from day to day. For most people over 45, doctors go by age, cycle changes and symptoms.

## Why noticing it helps

Putting a name to what’s happening can be a relief. It also opens up options, because many of these symptoms respond well to treatment.

## When to talk to your doctor

If several of these sound familiar and you’re in your late 30s or 40s, it’s worth raising. A few months of notes on your cycle, sleep and mood give your doctor a clearer picture than any single test.

## Sources

- The Menopause Society, patient information on perimenopause
- National Institute for Health and Care Excellence (NICE), Menopause guideline NG23
- U.S. National Institute on Aging, information on menopause symptoms', 2, array['perimenopause-and-beyond']::text[], array[]::text[], 'perimenopause-and-beyond', 61, false, 'published'),
  ('pmos-the-new-name', 'PMOS: why PCOS has a new name', 'The condition long called PCOS is being renamed PMOS. What the new name means, and why it fits better.', 'pmos', 'If you’ve been diagnosed with PCOS, or wondered whether you have it, you may start hearing a different name: PMOS, short for polyendocrine metabolic ovarian syndrome. PMOS (formerly PCOS) is the same condition. The name has changed to describe it more accurately.

## Why the old name didn’t fit

Polycystic ovary syndrome was named after what doctors saw on ultrasound: many small follicles on the ovaries. But those follicles aren’t really cysts, not everyone with the condition has them, and the name left out the parts that affect people most day to day.

## What the new name says

- **Polyendocrine:** it involves several hormones, not only ovarian ones. Insulin and androgens (hormones like testosterone) are central.
- **Metabolic:** it affects how the body handles blood sugar and energy. Insulin resistance is common, including in people who aren’t overweight.
- **Ovarian:** it still affects ovulation and cycles.

The change followed years of consultation with patients and clinicians around the world, many of whom felt the old name led to missed diagnoses and care that focused only on periods or fertility.

## Why it matters for you

Seeing it as a whole-body condition changes the conversation. It means asking about blood sugar, heart health, mood and sleep, not just cycles. It also explains why symptoms that seem unrelated, like irregular periods, acne, cravings and fatigue, often travel together.

## If you think it might be you

It’s common, often estimated to affect around 1 in 10 women of reproductive age, and many are never diagnosed. Irregular or missing periods, acne or extra hair growth, and difficulty getting pregnant are common reasons people are first checked. Your doctor can assess it with your history, an exam and blood tests.

## Sources

- International Evidence-based Guideline for the Assessment and Management of Polycystic Ovary Syndrome (2023), led by Monash University
- International consultation on renaming PCOS, led by Monash University
- ACOG, Polycystic Ovary Syndrome FAQ', 2, array['looking-for-answers']::text[], array[]::text[], 'looking-for-answers', 50, false, 'published'),
  ('sleep-and-mood', 'Why one rough night can colour the whole next day', 'Sleep and mood are closely linked. A short look at why a bad night makes everything feel harder.', 'energy-sleep', 'You know the feeling. After a rough night, small things feel bigger, patience runs thin, and the day seems to take more out of you. That’s not a character flaw. It’s one of the most consistent findings in sleep research.

## What’s going on

Sleep is when the brain and body recover. When you don’t get enough, the parts of the brain involved in noticing threats and reacting to emotions can become more reactive, while the parts that help you pause and put things in perspective work less well.

The result is a day where:

- Frustrations land harder and linger longer
- Motivation and energy dip
- Focus and memory feel patchier
- It’s harder to feel the good moments fully

It works in both directions, too. Stress and low mood can make it harder to sleep well, which is how a few rough nights can turn into a rough week.

## What tends to help

There’s no perfect formula, but a few basics make a real difference for many people:

- Keeping a similar wake-up time, even after a bad night
- Daylight, ideally outside, earlier in the day
- A wind-down time before bed with screens set aside
- Being kind to yourself the day after, and keeping expectations lighter

## When to talk to your doctor

If trouble sleeping lasts for weeks, if you wake up exhausted no matter how long you sleep, or if low mood is sticking around, it’s worth raising with your doctor. Your check-ins can show them the pattern at a glance.

## Sources

- Centers for Disease Control and Prevention, “About Sleep”
- National Heart, Lung, and Blood Institute, “Sleep Deprivation and Deficiency”
- Yoo S-S, et al. “The human emotional brain without sleep.” Current Biology, 2007', 2, array['energy-and-rhythm', 'listening-to-my-body']::text[], array['sleep-mood']::text[], 'energy-and-rhythm', 2, false, 'published'),
  ('starting-or-stopping-birth-control', 'Starting or stopping birth control: what can change', 'What to expect when you start, switch or stop hormonal birth control, without the scare stories.', 'birth-control', 'Hormonal birth control is one of the most studied medicines there is, and it works well for millions of people. It’s still normal to notice changes when you start, switch or stop, and knowing what to expect takes out some of the guesswork.

## When you start or switch

The first 2 to 3 months are an adjustment period. Common, usually temporary, changes include:

- Spotting or irregular bleeding
- Nausea, headaches or breast tenderness
- Changes in your skin, for better or worse
- Mood changes, for some people

If side effects don’t settle after about three months, or they’re affecting your life, talk to your doctor. There are many types and doses, and switching often helps.

## When you stop

With most methods, your natural cycle comes back within a few months. It can take longer after the injection.

A few things can surprise people:

- **Your first natural periods may be irregular** for a little while.
- **Symptoms from before may return.** Birth control is often used to manage acne or heavy, painful periods, so those can come back when you stop.
- **Some conditions show up for the first time.** Because hormonal birth control regulates bleeding, it can mask irregular cycles from conditions like PMOS (formerly PCOS). The birth control didn’t cause them. They were there underneath.

## When to talk to your doctor

If your period hasn’t come back three months after stopping, and you’re not pregnant, get it checked. If you’re stopping because you want to get pregnant, it’s a good time to ask about folic acid and a preconception check-up.

With methods that contain estrogen, get medical help straight away for a severe headache, chest pain, leg pain or swelling, or sudden changes in your vision.

## Sources

- ACOG, Combined Hormonal Birth Control FAQ
- ACOG, Progestin-Only Hormonal Birth Control FAQ
- NHS, Your contraception guide', 2, array[]::text[], array[]::text[], 'listening-to-my-body', 80, false, 'published'),
  ('stress-and-cravings', 'Stress, cravings and what’s happening in between', 'Why stressful days often come with stronger cravings, and why it isn’t about willpower.', 'stress', 'On the most stretched days, it’s common to want something sweet, salty or comforting more than usual. If you’ve ever blamed yourself for that, here’s the other side of the story.

## What’s going on

When you’re under stress, your body releases stress hormones, including cortisol. In the short term, they help you respond to whatever is asking a lot of you. When stress keeps going, cortisol can stay raised, and that’s linked with a bigger appetite and a stronger pull toward high-sugar and high-fat foods.

Foods like these can also feel soothing in the moment, which is part of why they’re so appealing on hard days. Tiredness adds to it: short sleep is linked with stronger hunger signals too.

So stronger cravings on stressful days are a very human response, not a lack of discipline.

## What tends to help

- Noticing the pattern, which your check-ins can show you
- Regular meals, so you’re not running on empty when stress peaks
- Small stress releases through the day: a walk, a few slow breaths, stepping outside
- Protecting sleep where you can

## When to talk to your doctor

If stress feels constant, if eating feels out of your control, or if big changes in appetite come without explanation, mention it to your doctor. You don’t have to have it all figured out first.

## Sources

- Harvard Health Publishing, “Why stress causes people to overeat”
- National Institute of Mental Health, “I’m So Stressed Out! Fact Sheet”
- Adam TC, Epel ES. “Stress, eating and the reward system.” Physiology & Behavior, 2007', 2, array['stress-and-my-body', 'energy-and-rhythm', 'looking-for-answers']::text[], array['stress-cravings']::text[], 'energy-and-rhythm', 3, false, 'published'),
  ('stress-and-your-cycle', 'How stress can show up in your cycle', 'A stressful month can mean a late period, a missed one, or a rougher week before it. Here’s the link.', 'stress', 'If your period has ever arrived late during a hard month, that’s not a coincidence. The parts of the brain that manage stress also help run your cycle.

## What’s going on

Your cycle is directed by the brain. The hypothalamus and pituitary gland send signals to the ovaries that lead to ovulation. The same area of the brain sits at the centre of your stress response, sometimes called the HPA axis (hypothalamus, pituitary and adrenal glands).

When stress is intense or goes on for a long time, the brain can turn down the signals to the ovaries. Ovulation may come later, or not happen that month. Because your period follows ovulation, it can arrive late or be skipped.

Stress can also show up as:

- Stronger premenstrual symptoms
- Periods that are heavier, lighter or more painful than usual
- Spotting between periods

## Stress isn’t only emotional

Your body counts many kinds of load as stress: poor sleep, illness, travel, intense training and not eating enough. They often arrive together, which is why cycles tend to shift during big life moments.

## What can help

Noting your cycle alongside how your weeks felt can show whether stress is a pattern for you. Sleep, regular meals and anything that genuinely lowers the pressure all help the signals settle.

## When to talk to your doctor

One late period in a stressful month is common. Talk to your doctor if you’ve missed three periods in a row, if your cycle has changed and stayed changed, or if there’s any chance you’re pregnant. Irregular cycles can have other causes, like thyroid problems or PMOS (formerly PCOS), and they’re worth checking.

## Sources

- ACOG, Abnormal Uterine Bleeding FAQ
- U.S. Office on Women’s Health, information on the menstrual cycle
- Endocrine Society, information on stress hormones', 2, array['stress-and-my-body', 'my-cycle', 'running-on-empty']::text[], array[]::text[], 'my-cycle', 30, false, 'published'),
  ('the-afternoon-crash', 'Why the afternoon crash happens', 'That 3pm slump is common, and it isn’t laziness. What blood sugar, sleep and your body clock have to do with it.', 'blood-sugar', 'Mid-afternoon, focus slips, your eyelids get heavy, and suddenly the snack drawer is all you can think about. Almost everyone knows this slump. It usually has more than one cause.

## What’s going on

Part of it is your body clock. Alertness naturally dips in the early afternoon, even on days you skip lunch. It’s built into the same daily rhythm that makes you sleepy at night.

Lunch can add to it. After a meal, blood sugar rises and the hormone insulin helps move that sugar into your cells. A meal that’s mostly quick-digesting carbohydrate, like white bread, pastries or a sweet drink on its own, tends to raise blood sugar quickly and let it fall quickly. Some people feel that fall as tiredness, shakiness or a sudden craving.

Short sleep makes all of it stronger. After a rough night, the afternoon dip hits harder and sweet foods get more appealing.

## Things that often help

- Pairing carbohydrates with protein, fibre or fat, which slows how quickly they’re absorbed
- Eating lunch at all, rather than running on coffee until mid-afternoon
- A short walk or some daylight after eating
- Protecting sleep where you can

None of this is about cutting foods out. It’s about giving your body something steady to run on.

## When to talk to your doctor

If you’re tired most of the day, very thirsty, peeing more than usual, or feel shaky and unwell a few hours after eating, mention it. Iron deficiency, thyroid changes and blood sugar problems can all feel like this, and simple blood tests can help.

## Sources

- U.S. National Institute of Diabetes and Digestive and Kidney Diseases (NIDDK), information on insulin and blood sugar
- U.S. National Heart, Lung, and Blood Institute, information on sleep and circadian rhythms
- Harvard T.H. Chan School of Public Health, The Nutrition Source, carbohydrates and blood sugar', 2, array['food-cravings-and-me']::text[], array[]::text[], 'energy-and-rhythm', 10, false, 'published'),
  ('the-week-before-your-period', 'Why the week before your period can feel so different', 'Energy, mood, sleep and cravings often shift in the days before a period. Here’s what’s changing.', 'cycle', 'If the days before your period feel heavier, slower or shorter-fused, you’re not imagining it, and you’re far from alone. Many people who menstruate notice changes in the week or two before a period.

## What’s changing

A cycle has two halves. After ovulation, the body makes more progesterone. If there’s no pregnancy, progesterone and estrogen both fall in the days before your period starts.

Those shifting hormone levels can affect how you feel. Common changes include:

- Lower energy or feeling more tired than usual
- Mood changes, like irritability, sadness or feeling tense
- Sleep that’s harder to settle into, or less restful
- Stronger cravings, often for sweet or salty foods
- Bloating or tender breasts

This is often called premenstrual syndrome, or PMS. How much it shows up varies a lot from person to person, and from cycle to cycle.

## Why noticing it helps

Seeing the pattern can take some of the sting out of it. A hard Tuesday feels different when you know it tends to land in the same part of your cycle. It also helps you plan: lighter days where you can, more rest, fewer big decisions.

## When to talk to your doctor

If premenstrual changes regularly get in the way of work, relationships or daily life, or if your mood drops very low, tell your doctor. A small number of people have a more severe form called premenstrual dysphoric disorder (PMDD), and there are treatments that help. Bringing a few months of check-ins can make that conversation easier.

## Sources

- American College of Obstetricians and Gynecologists, “Premenstrual Syndrome (PMS)” FAQ
- U.S. Office on Women’s Health, “Premenstrual syndrome (PMS)”
- MedlinePlus (U.S. National Library of Medicine), “Premenstrual syndrome”', 2, array['my-cycle', 'listening-to-my-body', 'energy-and-rhythm']::text[], array['premenstrual']::text[], 'my-cycle', 1, false, 'published'),
  ('waking-at-3am', 'Why you might wake at 3am', 'Waking in the small hours and lying there wired is common. A few of the usual reasons, and what can help.', 'energy-sleep', 'You fall asleep fine, then wake at 3 or 4am with your mind racing and can’t drift off again. It’s one of the most common sleep complaints, and it often has a few causes layered together.

## What might be behind it

- **Stress.** Cortisol, the hormone that helps you wake up, naturally starts rising in the early morning. When stress is high, sleep in those hours gets lighter and easier to break.
- **Alcohol.** A drink can help you fall asleep, but as it wears off, the second half of the night becomes lighter and more broken.
- **Hormone changes.** In the days before a period, and especially in perimenopause, falling estrogen and progesterone can make sleep more fragile. Night sweats can wake you too.
- **Eating patterns.** A very early dinner or a late, very sugary snack may play a part for some people, though the research here is less clear.
- **The simple things.** A full bladder, a restless partner, light or noise.

## What can help

- Keeping the same wake-up time, even after a bad night
- Not checking the clock or your phone, which tends to wake the mind up
- If you’ve been awake for what feels like 20 minutes, getting up to do something quiet in low light until you feel sleepy
- Noticing whether it lines up with your cycle, alcohol or stressful weeks

## When to talk to your doctor

If early waking happens most nights for a few weeks, or comes with low mood, loud snoring or gasping, or night sweats, mention it. Insomnia is very treatable, and one of the most effective approaches, cognitive behavioural therapy for insomnia (CBT-I), doesn’t involve medication.

## Sources

- American Academy of Sleep Medicine, patient information on insomnia
- U.S. National Heart, Lung, and Blood Institute, information on sleep deprivation
- The Menopause Society, information on sleep and night sweats', 2, array[]::text[], array[]::text[], 'energy-and-rhythm', 20, false, 'published'),
  ('what-cortisol-actually-does', 'What cortisol actually does', 'Cortisol gets blamed for a lot. It isn’t the enemy. It’s a daily rhythm that matters most when it’s thrown off.', 'stress', 'Cortisol is often called the stress hormone, and it has a rough reputation online. In reality, you couldn’t get through a day without it.

## Its daily job

Cortisol is made by the adrenal glands, which sit on top of your kidneys. It follows a rhythm: it rises sharply in the first hour after you wake, helping you feel alert, then falls through the day to its lowest point around bedtime.

Along the way it helps:

- Release energy, by raising blood sugar when you need it
- Keep blood pressure steady
- Calm inflammation
- Shape when you feel awake and when you feel sleepy

## When stress keeps it going

In a short burst of stress, cortisol rises, helps you respond, then settles. With ongoing stress, poor sleep or irregular routines, that rhythm can flatten or shift later. That can look like:

- Feeling groggy in the morning and alert at night
- Stronger cravings, especially for sweet or rich foods
- Lighter, more broken sleep
- Changes to your cycle

## A note on testing

You may see saliva or urine cortisol tests sold online. Cortisol changes hour to hour, so a single result is hard to interpret. Doctors use specific tests when they suspect a true adrenal condition, like Cushing’s syndrome or Addison’s disease, which are uncommon.

## What helps

The rhythm responds to rhythm: waking at a steady time, morning light, regular meals, movement and real breaks in the day.

## When to talk to your doctor

If you have unexplained weight changes, high blood pressure, easy bruising, dizziness when you stand, or deep fatigue that doesn’t lift with rest, see your doctor so they can check properly.

## Sources

- Endocrine Society, patient information on cortisol and adrenal conditions
- Cleveland Clinic, information on cortisol
- U.S. National Institute of Diabetes and Digestive and Kidney Diseases, information on Cushing’s syndrome and Addison’s disease', 2, array['stress-and-my-body']::text[], array[]::text[], 'stress-and-my-body', 31, false, 'published'),
  ('what-counts-as-a-regular-cycle', 'What counts as a regular cycle', 'Twenty-eight days is an average, not a rule. What a typical cycle looks like, and which changes are worth mentioning.', 'cycle', 'A lot of us grew up believing a cycle should be exactly 28 days. In reality, 28 is just an average, and plenty of healthy cycles look different.

## What’s typical for adults

- **Cycle length:** counted from the first day of one period to the first day of the next, usually anywhere from 21 to 35 days
- **Variation:** a few days’ difference from month to month is normal
- **Bleeding:** usually lasts 2 to 7 days, heaviest in the first day or two

In the first few years after periods start, and again in perimenopause, cycles are often less predictable.

## What your cycle can tell you

A regular cycle is a sign that ovulation is usually happening. That depends on your brain, ovaries, thyroid, metabolism and stress levels all working together, which is why a change in your cycle is sometimes the first sign that something else has shifted.

## Worth mentioning to your doctor

- Cycles shorter than 21 days or longer than 35 days
- Going 3 months without a period when you’re not pregnant
- Bleeding that soaks a pad or tampon every hour or two, or lasts more than 7 days
- Bleeding between periods or after sex
- Periods painful enough to stop you doing normal things
- A pattern that has changed and stayed changed

Keeping a simple record, like the dates of your periods and how you felt, makes that conversation much easier.

## Sources

- ACOG, Heavy Menstrual Bleeding FAQ
- ACOG, Abnormal Uterine Bleeding FAQ
- U.S. Office on Women’s Health, information on your menstrual cycle', 2, array['my-cycle']::text[], array[]::text[], 'my-cycle', 40, false, 'published'),
  ('what-is-perimenopause', 'Perimenopause: the years no one warned you about', 'The hormone shifts before menopause can start in your 40s, sometimes earlier, and last for years. What’s happening.', 'perimenopause', 'Menopause is a single point in time: 12 months in a row without a period. Perimenopause is the stretch of years leading up to it, and for many people it arrives earlier, and lasts longer, than they expected.

## When it starts

Perimenopause most often begins in your 40s, though some people notice changes in their late 30s. It lasts several years on average, and for some people closer to a decade. In the U.S., the average age of menopause is around 51.

## What’s happening

Your ovaries don’t wind down smoothly. Estrogen can swing higher and lower than before, month to month, while progesterone tends to fall as ovulation becomes less regular. Those swings, rather than a steady decline, explain a lot of the symptoms.

## What it can feel like

- Cycles that get shorter, longer, heavier or less predictable
- Hot flashes and night sweats
- Lighter, more broken sleep
- Mood changes, anxiety or irritability, sometimes new for you
- Brain fog and trouble finding words
- Joint aches, vaginal dryness and lower sex drive

Not everyone gets all of these, and many people don’t link them to hormones at first.

## You don’t have to wait it out

There are effective options, from changes to sleep, movement and routine to hormone therapy and non-hormonal medicines. The right choice depends on your symptoms and health history, and a doctor or menopause specialist can talk it through with you.

## When to talk to your doctor

If symptoms are affecting your sleep, work or relationships, make an appointment. See your doctor promptly for very heavy bleeding, bleeding between periods, or any bleeding after a full year without periods.

## Sources

- The Menopause Society, patient information on perimenopause
- U.S. National Institute on Aging, What Is Menopause?
- ACOG, The Menopause Years FAQ', 2, array['perimenopause-and-beyond']::text[], array[]::text[], 'perimenopause-and-beyond', 60, false, 'published'),
  ('whats-behind-a-craving', 'What’s actually behind a craving', 'Cravings aren’t a willpower problem. What your body and brain might be asking for.', 'food', 'Cravings usually get talked about as something to resist. But a craving is information. It’s your body and brain telling you something, and it helps to know what that might be.

## Common reasons

- **You’re hungry.** Skipping meals or eating too little earlier in the day is one of the most common reasons for strong cravings later.
- **You’re tired.** Short sleep raises ghrelin, a hormone that drives hunger, and lowers leptin, which helps you feel full. Sweet, energy-dense foods get more appealing.
- **You’re stressed.** Stress hormones can increase appetite, and comforting foods genuinely help people feel calmer in the moment.
- **Your cycle.** Many people crave more in the week before their period, when the body uses a little more energy.
- **Your last meal was mostly quick carbohydrates.** It can leave you hungry again soon after.
- **Habit and emotion.** A food linked to comfort, reward or a time of day. That’s human, not a flaw.

## Working with cravings, not against them

- Eating regularly, with protein, fibre and some fat, so you’re not running on empty
- Letting yourself have the food you want in a way that feels good, rather than banning it, which tends to make cravings stronger
- Noticing patterns: time of day, cycle day, sleep and stress

## When to talk to your doctor

If cravings come with intense thirst, peeing a lot, or feeling unwell after eating, ask to have your blood sugar checked. Cravings for ice, clay or other non-food things can be a sign of low iron. And if eating feels out of control or causes you distress, support is available and it helps.

## Sources

- U.S. National Heart, Lung, and Blood Institute, information on sleep and appetite
- Harvard Health Publishing, information on stress and eating
- American Society of Hematology, information on iron deficiency', 2, array['food-cravings-and-me']::text[], array[]::text[], 'food-cravings-and-me', 100, false, 'published'),
  ('wired-but-tired', 'Wired but tired', 'Drained all day and alert at night is a real, common pattern. What’s happening, and how to start unwinding it.', 'energy-sleep', 'You drag through the day on coffee, then get into bed and your brain lights up. Being exhausted and unable to rest at the same time feels contradictory, but it makes sense once you look at what stress does to the body.

## What’s going on

Under pressure, your body releases stress hormones like cortisol and adrenaline. They’re useful: they sharpen focus and give you energy to get through a demanding day. The trouble comes when the pressure doesn’t let up. Your body stays in a more alert mode, even when you finally stop.

A few things often keep the loop going:

- Caffeine later in the day, which can stay in your system for hours
- Screens and work late in the evening, which keep your mind in doing mode
- Going to bed at very different times from night to night
- No real pause during the day, so bedtime is the first chance your thoughts get

## Why you still feel tired

Poor sleep leaves you tired the next day, so you lean harder on caffeine and adrenaline, which makes the next night harder. It’s a loop, not a personal failing.

## What can help

- A caffeine cut-off, around eight hours before bed
- A wind-down time, even 20 minutes, with dim light and no work
- Morning daylight, which helps set your body clock
- Small pauses during the day, so stress has somewhere to go before bedtime

## When to talk to your doctor

If exhaustion lasts for weeks despite rest, or comes with low mood, a racing heart, or always feeling too hot or too cold, ask for a check-up. Thyroid problems, low iron and depression can all feel like this, and they’re worth ruling out.

## Sources

- U.S. National Heart, Lung, and Blood Institute, information on sleep
- American Psychological Association, information on stress and the body
- Sleep Foundation, information on caffeine and sleep', 2, array['running-on-empty']::text[], array[]::text[], 'running-on-empty', 21, false, 'published'),
  ('your-body-after-baby', 'Your body after baby: what’s still changing', 'Hormones, sleep, mood and periods can take months to settle after birth. What’s typical, and what’s worth checking.', 'fertility', 'There’s a lot of talk about getting your body back after a baby. What gets less attention is how much is still shifting inside, for months, not weeks.

## Hormones after birth

In pregnancy, estrogen and progesterone reach very high levels. Within days of birth they drop sharply. That fall, along with exhaustion, is part of why so many people feel tearful and overwhelmed in the first couple of weeks, often called the baby blues.

If you’re breastfeeding, the hormone prolactin stays high and estrogen stays low. That can mean vaginal dryness, lower sex drive and periods that stay away for months.

## Other changes that are common

- Periods returning anywhere from a few weeks to many months after birth, and sometimes feeling different
- Hair shedding around 3 to 4 months after birth
- Night sweats in the early weeks
- Changes in your pelvic floor, like leaking when you cough or laugh

## Worth checking with your doctor

- **Low mood or anxiety lasting more than 2 weeks**, or thoughts of harming yourself or your baby. Postpartum depression and anxiety are common and treatable. In the U.S., you can call or text the National Maternal Mental Health Hotline at 1-833-852-6262, or 988 in a crisis.
- **Feeling racing, shaky or unusually exhausted** in the months after birth, which can be a sign of postpartum thyroiditis
- **Leaking or heaviness in your pelvis** that isn’t improving, which pelvic floor physical therapy can help with

## Go gently

Your body did something enormous. Recovery isn’t a deadline, and getting back to baseline looks different for everyone.

## Sources

- ACOG, Postpartum Depression FAQ
- U.S. Office on Women’s Health, information on recovering from birth
- American Thyroid Association, information on postpartum thyroiditis', 2, array['after-baby', 'becoming-a-mom']::text[], array[]::text[], 'after-baby', 70, false, 'published'),
  ('your-fertile-window', 'Your fertile window, simply explained', 'There are about six days each cycle when pregnancy is possible. How to find them, and when to ask for help.', 'fertility', 'Whether you’re trying to get pregnant or just want to understand your cycle, the fertile window is worth knowing about. It’s shorter, and more specific, than many people assume.

## How it works

Once an egg is released at ovulation, it can be fertilized for about 12 to 24 hours. Sperm can survive in the body for up to 5 days. So the fertile window is about six days: the five days before ovulation and the day of ovulation itself. The two or three days just before ovulation are the most likely to lead to pregnancy.

## When ovulation happens

Ovulation usually happens about 14 days before your next period, not 14 days after your last one. In a 28-day cycle that’s around day 14. In a 32-day cycle, it’s closer to day 18.

Signs you might be near ovulation:

- Cervical mucus that’s clear, slippery and stretchy, like raw egg white
- A positive result on an ovulation predictor test
- A small rise in your resting temperature, which shows up just after ovulation
- A twinge of pain on one side, for some people

## When to ask for help

The general guidance is to see a doctor if you haven’t become pregnant after:

- 12 months of trying, if you’re under 35
- 6 months, if you’re 35 or older
- Sooner, if your cycles are irregular or absent, or you have a condition like PMOS (formerly PCOS) or endometriosis

Trying to conceive can be a lot to carry. It’s okay to ask for support early.

## Sources

- ACOG, Evaluating Infertility FAQ
- American Society for Reproductive Medicine, patient information on ovulation and fertility
- U.S. Office on Women’s Health, information on trying to conceive', 2, array[]::text[], array[]::text[], 'my-cycle', 71, false, 'published'),
  ('your-gut-and-hormones', 'How your gut helps clear hormones', 'Your liver and gut work together to process estrogen and move it out. What’s known, and what’s still being studied.', 'gut', 'When people think about hormones, they usually think about the ovaries or the thyroid. But your gut plays a part too, in how hormones are cleared once they’ve done their job.

## How it works

Once estrogen has been used, the liver packages it up so it can leave the body. Some leaves in urine. Some is sent into the gut in bile, to leave with your stool.

In the gut, certain bacteria make an enzyme that can unpack some of that estrogen, letting it be absorbed back into the blood. Researchers call the gut bacteria that affect estrogen in this way the estrobolome.

## What’s known and what isn’t

This research is new and moving quickly. Studies suggest the make-up of your gut bacteria may influence estrogen levels, and researchers are looking at links with conditions like endometriosis and PMOS (formerly PCOS). But there isn’t yet a test or product that can reliably tell you your estrobolome is off, or fix it. Be wary of anyone who says otherwise.

## What’s good for your gut anyway

- **Fibre**, from vegetables, fruit, beans, lentils and whole grains, which feeds helpful bacteria and keeps things moving
- **Regular bowel movements.** With constipation, waste, including used hormones, stays in the gut longer.
- **Variety.** A wider range of plant foods supports a wider range of bacteria.
- **Fermented foods**, like yogurt or kefir, if you enjoy them

## When to talk to your doctor

See your doctor for ongoing changes in your bowel habits, blood in your stool, unexplained weight loss, or stomach pain that doesn’t go away.

## Sources

- Review research on the estrobolome and estrogen metabolism (Baker, Al-Nakkash and Herbst-Kralovetz, Maturitas, 2017)
- Harvard T.H. Chan School of Public Health, The Nutrition Source, fibre and the microbiome
- NIDDK, information on constipation', 2, array[]::text[], array[]::text[], 'listening-to-my-body', 110, false, 'published')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, topic = excluded.topic, body = excluded.body, minutes = excluded.minutes, deck_ids = excluded.deck_ids, patterns = excluded.patterns, card_deck = excluded.card_deck, sort_order = excluded.sort_order, reviewed = excluded.reviewed, status = excluded.status;

update public.reads set status = 'archived' where id not in ('anxiety-from-nowhere', 'bloating-and-your-cycle', 'brain-fog', 'eating-enough', 'how-hormonal-birth-control-works', 'how-pmos-is-diagnosed', 'insulin-does-more-than-blood-sugar', 'perimenopause-signs-people-miss', 'pmos-the-new-name', 'sleep-and-mood', 'starting-or-stopping-birth-control', 'stress-and-cravings', 'stress-and-your-cycle', 'the-afternoon-crash', 'the-week-before-your-period', 'waking-at-3am', 'what-cortisol-actually-does', 'what-counts-as-a-regular-cycle', 'what-is-perimenopause', 'whats-behind-a-craving', 'wired-but-tired', 'your-body-after-baby', 'your-fertile-window', 'your-gut-and-hormones');

commit;
