-- Generated by scripts/reads/build-seed.mjs from content/reads. Do not edit by hand.
begin;

insert into public.reads (id, title, summary, body, minutes, deck_ids, patterns, card_deck, sort_order, reviewed, status) values
  ('sleep-and-mood', 'Why one rough night can colour the whole next day', 'Sleep and mood are closely linked. A short look at why a bad night makes everything feel harder.', 'You know the feeling. After a rough night, small things feel bigger, patience runs thin, and the day seems to take more out of you. That’s not a character flaw. It’s one of the most consistent findings in sleep research.

## What’s going on

Sleep is when the brain and body recover. When you don’t get enough, the parts of the brain involved in noticing threats and reacting to emotions can become more reactive, while the parts that help you pause and put things in perspective work less well.

The result is a day where:

- Frustrations land harder and linger longer
- Motivation and energy dip
- Focus and memory feel patchier
- It’s harder to feel the good moments fully

It works in both directions, too. Stress and low mood can make it harder to sleep well, which is how a few rough nights can turn into a rough week.

## What tends to help

There’s no perfect formula, but a few basics make a real difference for many people:

- Keeping a similar wake-up time, even after a bad night
- Daylight, ideally outside, earlier in the day
- A wind-down time before bed with screens set aside
- Being kind to yourself the day after, and keeping expectations lighter

## When to talk to your doctor

If trouble sleeping lasts for weeks, if you wake up exhausted no matter how long you sleep, or if low mood is sticking around, it’s worth raising with your doctor. Your check-ins can show them the pattern at a glance.

## Sources

- Centers for Disease Control and Prevention, “About Sleep”
- National Heart, Lung, and Blood Institute, “Sleep Deprivation and Deficiency”
- Yoo S-S, et al. “The human emotional brain without sleep.” Current Biology, 2007', 2, array['energy-and-rhythm', 'listening-to-my-body']::text[], array['sleep-mood']::text[], 'energy-and-rhythm', 2, false, 'published'),
  ('stress-and-cravings', 'Stress, cravings and what’s happening in between', 'Why stressful days often come with stronger cravings, and why it isn’t about willpower.', 'On the most stretched days, it’s common to want something sweet, salty or comforting more than usual. If you’ve ever blamed yourself for that, here’s the other side of the story.

## What’s going on

When you’re under stress, your body releases stress hormones, including cortisol. In the short term, they help you respond to whatever is asking a lot of you. When stress keeps going, cortisol can stay raised, and that’s linked with a bigger appetite and a stronger pull toward high-sugar and high-fat foods.

Foods like these can also feel soothing in the moment, which is part of why they’re so appealing on hard days. Tiredness adds to it: short sleep is linked with stronger hunger signals too.

So stronger cravings on stressful days are a very human response, not a lack of discipline.

## What tends to help

- Noticing the pattern, which your check-ins can show you
- Regular meals, so you’re not running on empty when stress peaks
- Small stress releases through the day: a walk, a few slow breaths, stepping outside
- Protecting sleep where you can

## When to talk to your doctor

If stress feels constant, if eating feels out of your control, or if big changes in appetite come without explanation, mention it to your doctor. You don’t have to have it all figured out first.

## Sources

- Harvard Health Publishing, “Why stress causes people to overeat”
- National Institute of Mental Health, “I’m So Stressed Out! Fact Sheet”
- Adam TC, Epel ES. “Stress, eating and the reward system.” Physiology & Behavior, 2007', 2, array['energy-and-rhythm', 'looking-for-answers']::text[], array['stress-cravings']::text[], 'energy-and-rhythm', 3, false, 'published'),
  ('the-week-before-your-period', 'Why the week before your period can feel so different', 'Energy, mood, sleep and cravings often shift in the days before a period. Here’s what’s changing.', 'If the days before your period feel heavier, slower or shorter-fused, you’re not imagining it, and you’re far from alone. Many people who menstruate notice changes in the week or two before a period.

## What’s changing

A cycle has two halves. After ovulation, the body makes more progesterone. If there’s no pregnancy, progesterone and estrogen both fall in the days before your period starts.

Those shifting hormone levels can affect how you feel. Common changes include:

- Lower energy or feeling more tired than usual
- Mood changes, like irritability, sadness or feeling tense
- Sleep that’s harder to settle into, or less restful
- Stronger cravings, often for sweet or salty foods
- Bloating or tender breasts

This is often called premenstrual syndrome, or PMS. How much it shows up varies a lot from person to person, and from cycle to cycle.

## Why noticing it helps

Seeing the pattern can take some of the sting out of it. A hard Tuesday feels different when you know it tends to land in the same part of your cycle. It also helps you plan: lighter days where you can, more rest, fewer big decisions.

## When to talk to your doctor

If premenstrual changes regularly get in the way of work, relationships or daily life, or if your mood drops very low, tell your doctor. A small number of people have a more severe form called premenstrual dysphoric disorder (PMDD), and there are treatments that help. Bringing a few months of check-ins can make that conversation easier.

## Sources

- American College of Obstetricians and Gynecologists, “Premenstrual Syndrome (PMS)” FAQ
- U.S. Office on Women’s Health, “Premenstrual syndrome (PMS)”
- MedlinePlus (U.S. National Library of Medicine), “Premenstrual syndrome”', 2, array['my-cycle', 'listening-to-my-body', 'energy-and-rhythm']::text[], array['premenstrual']::text[], 'my-cycle', 1, false, 'published')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, body = excluded.body, minutes = excluded.minutes, deck_ids = excluded.deck_ids, patterns = excluded.patterns, card_deck = excluded.card_deck, sort_order = excluded.sort_order, reviewed = excluded.reviewed, status = excluded.status;

update public.reads set status = 'archived' where id not in ('sleep-and-mood', 'stress-and-cravings', 'the-week-before-your-period');

commit;
