// Builds supabase/seed/reads.sql from the short reads in content/reads/*.md.
//
//   node scripts/reads/build-seed.mjs
//
// Each read is a markdown file with a small header:
//   id, title, summary, topic, minutes, order, decks (comma list), patterns (comma
//   list), card_deck, reviewed (true once the clinical advisor has checked it).
// Reads removed from the folder are archived, not deleted.

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const dir = `${root}/content/reads`;
const output = `${root}/supabase/seed/reads.sql`;

const sql = (v) => (v == null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const arr = (xs) => `array[${xs.map(sql).join(', ')}]::text[]`;
const list = (s) => (s ? s.split(',').map((x) => x.trim()).filter(Boolean) : []);

// Keep in step with TOPICS in src/lib/reads.ts.
const TOPICS = ['blood-sugar', 'energy-sleep', 'stress', 'cycle', 'pmos', 'perimenopause', 'fertility', 'birth-control', 'mood', 'food', 'gut'];

const errors = [];
const reads = readdirSync(dir)
  .filter((f) => f.endsWith('.md'))
  .map((file) => {
    const text = readFileSync(`${dir}/${file}`, 'utf8').replace(/\r\n/g, '\n');
    const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
    if (!m) {
      errors.push(`${file}: missing the --- header block`);
      return null;
    }
    const meta = Object.fromEntries(
      m[1].split('\n').map((line) => {
        const i = line.indexOf(':');
        return [line.slice(0, i).trim(), line.slice(i + 1).trim()];
      }),
    );
    for (const key of ['id', 'title']) if (!meta[key]) errors.push(`${file}: missing "${key}"`);
    if (!TOPICS.includes(meta.topic)) errors.push(`${file}: "topic" must be one of ${TOPICS.join(', ')}`);
    if (/—/.test(text)) errors.push(`${file}: contains an em dash (not allowed in Daily Few copy)`);
    return {
      id: meta.id,
      title: meta.title,
      summary: meta.summary,
      topic: meta.topic,
      body: m[2].trim(),
      minutes: Number(meta.minutes) || 2,
      order: Number(meta.order) || 0,
      decks: list(meta.decks),
      patterns: list(meta.patterns),
      cardDeck: meta.card_deck || null,
      reviewed: meta.reviewed === 'true',
    };
  })
  .filter(Boolean);

if (errors.length) {
  console.error(`Not written. Fix these first:\n- ${errors.join('\n- ')}`);
  process.exit(1);
}

const out = [
  `-- Generated by scripts/reads/build-seed.mjs from content/reads. Do not edit by hand.`,
  'begin;',
  '',
  'insert into public.reads (id, title, summary, topic, body, minutes, deck_ids, patterns, card_deck, sort_order, reviewed, status) values',
  reads
    .map(
      (r) =>
        `  (${sql(r.id)}, ${sql(r.title)}, ${sql(r.summary)}, ${sql(r.topic)}, ${sql(r.body)}, ${r.minutes}, ${arr(r.decks)}, ${arr(r.patterns)}, ${sql(r.cardDeck)}, ${r.order}, ${r.reviewed}, 'published')`,
    )
    .join(',\n'),
  'on conflict (id) do update set title = excluded.title, summary = excluded.summary, topic = excluded.topic, body = excluded.body, minutes = excluded.minutes, deck_ids = excluded.deck_ids, patterns = excluded.patterns, card_deck = excluded.card_deck, sort_order = excluded.sort_order, reviewed = excluded.reviewed, status = excluded.status;',
  '',
  `update public.reads set status = 'archived' where id not in (${reads.map((r) => sql(r.id)).join(', ')});`,
  '',
  'commit;',
  '',
];

mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, out.join('\n'));
console.log(`Wrote ${output}\n${reads.length} reads (${reads.filter((r) => !r.reviewed).length} not yet reviewed).`);
